### ISSUE TITLE
How to define "contributor"

### ISSUE THREAD

**Issue by choldgraf** [choldgraf/github-activity#13]
In a recent BinderHub issue, @betatim brought up a good point that we should find a balance between "everybody is a contributor" and "nobody is a contributor".

Right now, this repo defines contributor as:

* Anybody that makes > 1 comment in a time-span (https://github.com/choldgraf/github-activity/blob/master/github_activity/github_activity.py#L178)
* Anybody who opens a PR or issue (https://github.com/choldgraf/github-activity/blob/master/github_activity/github_activity.py#L255)

However we've never rigorously thought this one through. This is an issue to be more thoughtful about it.

@betatim's suggestion was to increase the bar to "comment on more than one issue not created by you". What if expanded that to "opened a PR that was merged within a time window"?

The only drawback from this is that IMO a person that only comments on 1 issue, but comments in an engaged and ongoing way, is still quite helpful, and this would miss that person. We could also include something like ">= 4 messages on any single issue, or >= 2 messages across other people's issues"

@betatim what do you think?

**Comment by betatim** [comment]
In the below I am thinking of a project as something that needs "effort". This "effort" is a scarce resource, because the main ingredient in this "effort" is time (or something like it). If we did a [SVD](https://en.wikipedia.org/wiki/Singular_value_decomposition) of "effort" the "time" component would get a large weight.

Requesting a feature "costs" effort (you are withdrawing from the projects account) and implementing a feature "adds" effort (you are making a deposit). A contributor is someone who makes a deposit (or many).

Getting a PR merged should make you a contributor. I think counting the opening of a PR would be weird because your name appears in the list when you open it and not when it gets merged (potentially two different periods). When it gets merged is when it shows up as a new feature in the changelog. You should be listed as a contributor when the PR is listed in the changelog. However listing you in two periods once for opening and once for it getting merged feels like double counting.

I think of almost all of the "me too" or "is there an update yet?" type comments in issues as "spam" and not a contribution. So they should be excluded. Similarly reporting a bug or requesting a new feature are "costs". I'd be fine with this because requesting a new feature (no matter how great that feature is) costs the project effort. I am assuming that a project needs "effort" more than it needs feature requests or bug reports or put a different way that a list of great features is worth nothing if you don't have the "effort" to implement them. Projects are made of implemented features and fixed bugs, not requested or reported ones.

People who report a bug and then get a PR (any kind!) merged are counted as contributors. People who request a new feature and get a PR merged (any kind!) are also counted as contributors. This means we have them covered.

People who don't get PRs merged can still be contributors because they are helping people via discussions in issues. If they are doing this they are (very) likely to be involved in several issues or PRs in this role as helper.

It isn't perfect but a good start.

**Comment by choldgraf** [comment]
Thanks for the input! In general I agree, a few quick thoughts -

* It's only counting PR authors when the PR has been *merged* within the date window, so we are covered there.
* I think I value people opening bugs and feature requests a bit more :-)  IMO that's a really important role that less-involved members of the community play. I'd much rather have a community that's consistently surfacing bugs and reporting them, rather than silently getting frustrated and not using the tool. And having a user interaction where I can say "hey I think I fixed this, can you try this branch and let me know if it works" and have them be quick and responsive is super useful to me at least, even though that user is not technically writing code.
* I agree with the "me too" etc comments not being super helpful. It's just hard to quantify that without adding a lot of complexity to this tool (which I want to keep pretty simple)

What if we compromised and went something like:

Any contributor within a range of time is someone who:

* Had their PR merged in that window
* Commented on >= 2 issues that weren't theirs
* Commented more than 5 times on any one issue

What do you think?

**Comment by betatim** [comment]
I like the new suggestion.

I think by setting comment requirements to >1 we remove a very large fraction of "me too" comments and only lose a small fraction of contributors (mostly because contributors are very likely to do more than just comment).

Bug reports and feature requests are super useful and part of a healthy project and community. I'm trying to draw a line between two closely related roles: user and contributor. The same human can be in both roles and there is no ranking of the roles as one being more important. As you say you need both (a project might move forward when "features" are implemented, but a project dies if it has no users!).

My hope is that rules that require a bit more interaction beyond writing the feature request/bug report are naturally ticked off if you do a good job of feature requesting. Basically that it models/captures what happens anyway with a new feature request: implementation that requires feedback, discussion, research in past issues/PRs. A bit like in discourse where you hardly ever notice "the rules" if you are doing what the software thinks you should be doing.

**Comment by choldgraf** [comment]
Yeah, I agree with you - I think ultimately we are drawing a hard boundary (contributor vs. not-a-contributor) within a fuzzy region so there will always be semi-arbitrary choices to make there. I like your framing in terms of "what is the scarce resource in the community?"

I'm gonna close this PR since we have the PR merged, but I'm happy to re-visit this sometime, it's an interesting discussion!
